# Generated by Django 3.2.7 on 2021-09-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20210921_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#FFF2A7', max_length=200),
        ),
    ]
